### ISSUE TITLE
Duplication of quote elements text inside of analogues

### ISSUE THREAD

**Issue by ChiaraMartignano** [evt-project/evt-viewer#3] opened 2018-10-05 09:45 UTC
The text of a quote element (i.e. a part of the critical text that corresponds to an entry of the sources apparatus) gets duplicated when it is inside of an analogue element.

**Comment by federicaspinelli** [comment] 2020-03-31 16:33
This entry refers to a bug handled in issue #9
Duplicate of #9 .

**Closed by federicaspinelli** 2020-03-31 16:33 UTC
Labels: bug
